/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5cf34752a8e9561a0d3360
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import { DateTimePicker } from "material-ui-pickers";

// Custom Actions


// START IMPORT ACTIONS
import Model1Actions from "../redux/actions/Model1Actions";

// END IMPORT ACTIONS

/** APIs

* actionsModel1.create
*	@description CRUD ACTION create
*
* actionsModel1.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsModel1.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*

**/

class Model1Edit extends Component {
  // Init model1
  constructor(props) {
    super(props);
    this.state = {
      model1: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsModel1.loadModel1(this.props.match.params.id);
    }
    
  }

  // Insert props model1 in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      model1: props.model1
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.model1._id) {
      this.props.actionsModel1.saveModel1(this.state.model1).then(data => {
        this.props.history.push("/model1s/");
      });
    } else {
      this.props.actionsModel1.createModel1(this.state.model1).then(data => {
        this.props.history.push("/model1s/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Model1 Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="free"
            label="Free"
            value={this.state.model1.free || ""}
            onChange={Utils.handleChange.bind(this, "model1")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="name"
            label="Name"
            value={this.state.model1.name || ""}
            onChange={Utils.handleChange.bind(this, "model1")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.model1.name && this.state.model1.name === ""
              ? { error: true }
              : {})}
          />
          
          <DateTimePicker
            id="testing1"
            label="Testing1"
            className="mt-20 mb-20"
            ampm={false}
            value={
              this.state.model1.testing1
                ? new Date(this.state.model1.testing1)
                : null
            }
            onChange={Utils.handleChangeDate.bind(this, "model1", "testing1")}
            fullWidth
            autoOk
            disableFuture
          />
          

          {/* Footer */}
          <div className="footer-card">
            <Link to="/model1s/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsModel1: bindActionCreators(Model1Actions, dispatch),
  };
};

// Validate types
Model1Edit.propTypes = { 
  actionsModel1: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    model1: state.Model1EditReducer.model1
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Model1Edit);
